<?php

namespace CoachBundle\Repository;

/**
 * CoachAdvertisementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachAdvertisementsRepository extends \Doctrine\ORM\EntityRepository
{
}
