<?php

namespace CoachBundle\Repository;

/**
 * CoachEventDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachEventDatesRepository extends \Doctrine\ORM\EntityRepository
{
}
