<?php

namespace CoachBundle\Repository;

/**
 * CoachCoursePlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachCoursePlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
