<?php

namespace CoachBundle\Repository;

/**
 * CoachCourseReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachCourseReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
