<?php

namespace CoachBundle\Repository;

/**
 * MovementRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovementRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
