<?php

namespace CoachBundle\Repository;

/**
 * NumberOfPersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberOfPersonsRepository extends \Doctrine\ORM\EntityRepository
{
}
