<?php

namespace CoachBundle\Repository;

/**
 * PrimaryObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimaryObjectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
