<?php

namespace CoachBundle\Repository;

/**
 * SessionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
