<?php

namespace ClubBundle\Repository;

/**
 * ClubNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubNetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
