<?php

namespace ClubBundle\Repository;

/**
 * ClubActivitieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubActivitieRepository extends \Doctrine\ORM\EntityRepository
{
}
