<?php

namespace ClubBundle\Repository;

/**
 * ClubActivitiesAmenitiesConfortServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubActivitiesAmenitiesConfortServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
