<?php

namespace ClubBundle\Repository;

/**
 * ClubReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
