<?php

namespace ClubBundle\Repository;

/**
 * ClubBillingInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubBillingInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
