<?php

namespace ClubBundle\Repository;

/**
 * ClubTimeTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubTimeTableRepository extends \Doctrine\ORM\EntityRepository
{
}
