<?php

namespace ClubBundle\Repository;

/**
 * ClubEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClubEvents(array $args)
    {
        
        $query = $this->createQueryBuilder('E');                
        
        if (array_key_exists('idClub', $args))
        {
            $query = $query->where('E.idClub = :ID_CLUB')
                    ->setParameter('ID_CLUB', $args['idClub']);
        }
        
        if (array_key_exists('status', $args))
        {
            $query = $query->andWhere("E.status IN ({$args['status']})");
        }
        
        if (array_key_exists('month', $args))
        {
            $query = $query->join('E.dates', 'ED')
                    ->andWhere("ED.date >= :FROM_DATE AND ED.date <= :TO_DATE")
                    ->setParameter('FROM_DATE', $args['month']['from'])
                    ->setParameter('TO_DATE', $args['month']['to']);
            
            if (array_key_exists('orderBy', $args) && $args['orderBy'])
            {
                if (array_key_exists('date', $args['orderBy']) && $args['orderBy']['date'])
                {
                    $query = $query->orderBy('ED.date', $args['orderBy']['date']);
                }
            }
        }
        
        if (array_key_exists('limit', $args))
        {
            $query = $query->setMaxResults($args['limit']);
        }
        
        return $query->getQuery()->getResult();
    }
}
