<?php

namespace ClubBundle\Repository;

/**
 * ClubTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
