<?php

namespace ClubBundle\Repository;

/**
 * ClubMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
