<?php

namespace ClubBundle\Repository;

/**
 * ClubActivitieThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubActivitieThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
