<?php

namespace ClubBundle\Repository;

/**
 * ClubServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
