<?php

namespace ClubBundle\Repository;

/**
 * ClubAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
