<?php

namespace ClubBundle\Repository;

/**
 * ClubSubscriptionInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubSubscriptionInvoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
