<?php

namespace ClubBundle\Repository;

/**
 * ClubEquipementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubEquipementRepository extends \Doctrine\ORM\EntityRepository
{
}
