<?php

namespace ClubBundle\Repository;

/**
 * ClubEventDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubEventDatesRepository extends \Doctrine\ORM\EntityRepository
{
}
