<?php

namespace ClubBundle\Repository;

/**
 * ClubConfortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubConfortRepository extends \Doctrine\ORM\EntityRepository
{
}
