<?php

namespace ClubBundle\Repository;

/**
 * ListClubNetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListClubNetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
