<?php

namespace ClubBundle\Repository;

/**
 * ListClubFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListClubFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
