<?php

namespace ClubBundle\Repository;

/**
 * ListClubTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListClubTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
