<?php

namespace CommunBundle\Repository;

/**
 * CustomerReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerReviewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMoyReviews(array $args)
    {
        $query = $this->createQueryBuilder("CR")
                ->select('COALESCE(SUM(CR.note), 0) AS note, COUNT(CR) AS comments')
                ->where('CR.status = :STATUS')
                ->setParameter("STATUS", $args['status']);
        
        if (array_key_exists('clubInfo', $args))
        {
            $query = $query->andWhere("CR.club_info = :CLUB")
                    ->setParameter("CLUB", $args['club_info']);
        }
        
        if (array_key_exists('coach_info', $args))
        {
            $query = $query->andWhere("CR.coach_info = :COACH")
                    ->setParameter("COACH", $args['coach_info']);
        }
        
        $result = $query->getQuery()->getSingleResult();
        
        $nbr_comments   = $result['comments']; 
        $sum_reviws     = $result['note'];
        
        return $sum_reviws / $nbr_comments;
    }    
    
}
