<?php

namespace CommunBundle\Repository;

/**
 * ListAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListAdRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLastAd($limit = 2)
    {
        $sql = "select ad ";
        $from = " from CommunBundle\Entity\ListAd as ad,";
        $where = " where ad.status =1 and";
        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where . " order BY ad.dateAdd DESC ";
        $qb = $this->getEntityManager()->createQuery($query)
            ->setMaxResults($limit);
        return $qb->getResult() ;

    }


}
