<?php

namespace CommunBundle\Repository;

/**
 * ListAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
