<?php

namespace CommunBundle\Repository;

/**
 * ListCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCityRepository extends \Doctrine\ORM\EntityRepository
{

    public function findListCity($id)
    {
        $sql = "select city.name as name, city.id as id ";
        $from = " from CommunBundle\Entity\ListCity as city,";
        $where = " where city.idDepartement =".$id." and";

        $where = substr($where, 0, -4);
        $from = substr($from, 0, -1);
        $query = $sql . $from . $where ;
        $qb = $this->getEntityManager()->createQuery($query);
        return $qb->getResult() ;

    }


}
