<?php

namespace CommunBundle\Repository;

/**
 * ListCourseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCourseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
