<?php

namespace CommunBundle\Repository;

/**
 * ListRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
