<?php

namespace CommunBundle\Repository;

/**
 * ListCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
