<?php

namespace CommunBundle\Repository;

/**
 * ListTypeAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListTypeAdRepository extends \Doctrine\ORM\EntityRepository
{
}
