<?php

namespace CommunBundle\Repository;

/**
 * ListDepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListDepartementRepository extends \Doctrine\ORM\EntityRepository
{
}
