<?php

namespace CommunBundle\Repository;

/**
 * ListPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
