<?php

namespace CommunBundle\Repository;

/**
 * ListCivilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListCivilityRepository extends \Doctrine\ORM\EntityRepository
{
}
